[tool.poetry]
name = "based-api"
version = "0.2.0"
description = "based-api is a package that serves predictions from the Boost-Assissted Stream Estimator for Depth (BASED).BASED is an XGBoost regressor deployed using Streamlit. This package is designed for making channel depth predictions using channel width, slope, and discharge."
authors = ["Jake Gearon <jake.gearon@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
xgboost = "^2.1.1"
scikit-learn = "^1.5.2"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
